### ISSUE TITLE
Change license to real OSS license

### ISSUE THREAD

**Issue by david-a-wheeler** [khinsen/leibniz#1]
The current license isn't an OSS license, at least because it has a restriction on use.

Also, even if your software *starts* awful, it might not stay that way... yet the license will still be the same.

I suggest you pick a standard, widely-use OSS license if that's what you're trying to do.

**Comment by khinsen** [comment]
What I am trying to do at this time is concentrate on the development of Leibniz and not make any licensing mistake that I could regret later.

My goal is to make Leibniz usable to as many people as possible. Given the current mess of not-interoperable OSS licenses, this requires a lot of thought, and probably a split of the repository into distinct parts with different licenses. At least one for the current implementation (GPL family or BSD family) and one for the "standard library" of Leibniz contexts (CC family) that could be used by other implementations. Perhaps a third one for the definition of Leibniz itself, though I suspect this simply falls under copyright since it is not executable.

All that is simply not my priority at this time. I didn't even announced Leibniz anywhere yet, since I consider it much too incomplete. I promise that I will change to a "real" license later!
